#!/bin/sh

injection_die() { printf 'injection-contract: %s\n' "$*" >&2; return 1; }
injection_legal_frequencies() { awk '/\* [0-9]+ MHz/ && $0 !~ /\(disabled\)/ && $0 !~ /\(radar detection\)/ && $0 !~ /\(no IR\)/ { for (i=1;i<=NF;i++) if ($i == "MHz") printf "%s%s", sep, $(i-1), sep=" " } END { if (sep != "") print "" }' "$1"; }
injection_band_for_frequency() { case $1 in 24[0-9][0-9]) printf '%s\n' 2.4;; 5[0-8][0-9][0-9]) printf '%s\n' 5;; 59[0-9][0-9]|6[0-9][0-9][0-9]|7[01][0-9][0-9]) printf '%s\n' 6;; *) injection_die "unsupported frequency: $1";; esac; }
injection_tag() { printf 'MT7927-INJ|%s|%s|%s>%s|%s|%06d\n' "$1" "$2" "$3" "$4" "$5" "$6"; }
injection_delivery_percent() { [ "$2" -gt 0 ] || { injection_die 'sent frame count must be positive'; return 1; }; printf '%s\n' "$((100 * $1 / $2))"; }
injection_quote_command() { printf '%s' "$1"; shift; for arg do printf ' %s' "$arg"; done; printf '\n'; }
injection_run() { if [ "${INJECTION_DRY_RUN:-1}" -eq 1 ]; then printf 'DRY-RUN: '; injection_quote_command "$@"; else "$@"; fi; }
injection_require_command() { command -v "$1" >/dev/null 2>&1 || injection_die "required command not found: $1"; }
injection_frequency_is_legal() { case " $1 " in *" $2 "*) return 0;; *) return 1;; esac; }

injection_validate_evidence()
{
	[ "$#" -eq 7 ] || { injection_die 'internal validation requires probe, send, receiver, reflection, window, metadata, and run ID'; return 1; }
	if result=$(awk -F '\t' -v probe_file="$1" -v send_file="$2" -v receiver_file="$3" -v reflection_file="$4" -v window_file="$5" -v meta_file="$6" -v run="$7" -v candidate='ca013156cfc2e7641e273a5ea0f6ece896facd43' '
	function die(m) { printf "injection-contract: %s\n", m; bad=1; exit 1 }
	function ident(v) { return v ~ /^[A-Za-z0-9][A-Za-z0-9._-]*$/ }
	function integer(v) { return v ~ /^[0-9]+$/ }
	function time(v) { return v ~ /^[0-9]+([.][0-9]+)?$/ }
	function mac(v) { return v ~ /^([0-9A-Fa-f][0-9A-Fa-f]:){5}[0-9A-Fa-f][0-9A-Fa-f]$/ }
	function center(v) { v+=0; return v==2484 || (v>=2412 && v<=2472 && (v-2412)%5==0) || (v>=5000 && v<=5895 && (v-5000)%5==0) || (v>=5955 && v<=7115 && (v-5955)%20==0) }
	function band(v) { v+=0; return v<2500 ? "2.4" : v<5900 ? "5" : "6" }
	function tag(v,a,b,n) { n=split(v,a,"[|]"); if(n!=6 || a[1]!="MT7927-INJ" || a[2]!=run || (a[3]!="pre" && a[3]!="post") || split(a[4],b,">")!=2 || !integer(b[1]) || !integer(b[2]) || !center(b[1]) || !center(b[2]) || b[1]==b[2] || (a[5]!="unicast" && a[5]!="broadcast") || a[6]!~/^[0-9][0-9][0-9][0-9][0-9][0-9]$/) return 0; tside=a[3]; tsrc=b[1]; tdst=b[2]; tclass=a[5]; return 1 }
	function key(a,b,c) { return a SUBSEP b SUBSEP c }
	function need(a,b,c,m,x) { x=meta[key(a,b,c)]; if(x=="") die("missing metadata: " m); return x }
	function snapshot(which,list,a,n,i,v) { n=split(list,a," "); if(n<1) die("empty legal-frequency snapshot"); for(i=1;i<=n;i++){v=a[i]; if(!integer(v)||!center(v)) die("invalid legal channel center: " v); if(which=="tx") txlegal[v]=1; else rxlegal[v]=1} }
	FILENAME==probe_file && FNR==1 { if($0!="tag\ttx_frequency_mhz\tlisten_frequency_mhz\tclass\texpectation\treceiver_session_id\texpected_transmitter_addr") die("invalid probe-plan header"); hp=1; next }
	FILENAME==send_file && FNR==1 { if($0!="tag\tsend_status\tsender_ts") die("invalid send-results header"); hs=1; next }
	FILENAME==receiver_file && FNR==1 { if($0!="tag\tfrequency_mhz\treceiver_ts\tsession_id\tobserved_transmitter_addr\tframe_control\tsequence_control") die("invalid receiver header"); hr=1; next }
	FILENAME==reflection_file && FNR==1 { if($0!="tag\tlocal_state\tlocal_ts\tsession_id\tobserved_transmitter_addr\tframe_control\tsequence_control") die("invalid local-reflection header"); hl=1; next }
	FILENAME==window_file && FNR==1 { if($0!="receiver_session_id\tstart_ts\tready_ts\tstop_ts\tcollect_ts\towner_token\tpid\tstart_identity\tready_nonce\tverified_listen_frequency\tcapture_packets\tcapture_drops\tcapture_liveness\treceiver_host\treceiver_phy\treceiver_interface\treceiver_device\treceiver_radio\tcapture_command\tpcap_path\tpcap_sha256") die("invalid window header"); hw=1; next }
	FILENAME==meta_file && FNR==1 { if($0!="kind\tid\tfield\tvalue") die("invalid run-metadata header"); hm=1; next }
	FILENAME==probe_file { if(NF!=7 || !tag($1) || !integer($2) || !integer($3) || !center($2) || !center($3) || $4!=tclass || ($5!="present" && $5!="absent") || !ident($6) || !mac($7)) die("malformed probe-plan row " FNR); if(plan[$1]++) die("duplicate probe tag: " $1); expected=tside=="pre"?tsrc:tdst; other=tside=="pre"?tdst:tsrc; if($2!=expected || ($5=="present" && $3!=$2) || ($5=="absent" && $3!=other)) die("probe-plan mismatch: " $1); tx[$1]=$2; listen[$1]=$3; klass[$1]=$4; expect[$1]=$5; session[$1]=$6; addr[$1]=$7; opposite[$1]=other; if($5=="present"){matrix[$2 SUBSEP $3 SUBSEP $4]++; total++; bands[band($2)]=1; required_negative[$2 SUBSEP other SUBSEP $4]=1}else negative[$2 SUBSEP $3 SUBSEP $4]=1; next }
	FILENAME==send_file { if(NF!=3 || !tag($1) || ($2!="SENT" && $2!="FAILED") || !time($3)) die("malformed send-result row " FNR); if(sent[$1]++) die("duplicate send tag: " $1); send_state[$1]=$2; send_ts[$1]=$3; next }
	FILENAME==receiver_file { if(NF!=7 || !tag($1) || !integer($2) || !center($2) || !time($3) || !ident($4) || !mac($5) || $6!~/^[0-9a-f][0-9a-f][0-9a-f][0-9a-f]$/ || $7!~/^[0-9a-f][0-9a-f][0-9a-f][0-9a-f]$/) die("malformed receiver row " FNR); if(rcv[$1]++) die("duplicate receiver tag: " $1); rf[$1]=$2; rt[$1]=$3; rs[$1]=$4; ra[$1]=$5; rfc[$1]=$6; rsc[$1]=$7; next }
	FILENAME==reflection_file { if(NF!=7 || !tag($1) || ($2!="LOCAL_ACKED" && $2!="LOCAL_FAILED" && $2!="LOCAL_REFLECTED") || !time($3) || !ident($4) || !mac($5) || $6!~/^[0-9a-f][0-9a-f][0-9a-f][0-9a-f]$/ || $7!~/^[0-9a-f][0-9a-f][0-9a-f][0-9a-f]$/) die("malformed local-reflection row " FNR); if(local_seen[$1]++) die("duplicate local-reflection tag: " $1); ls[$1]=$4; la[$1]=$5; lfc[$1]=$6; lsc[$1]=$7; next }
	FILENAME==window_file { if(NF!=21 || !ident($1) || !time($2) || !time($3) || !time($4) || !time($5) || !ident($6) || !integer($7) || !ident($8) || !ident($9) || !integer($10) || !center($10) || !integer($11) || !integer($12) || $13!="healthy" || !ident($15) || !ident($16) || !ident($17) || !ident($18) || $19=="" || $20=="" || $21!~/^[0-9a-f][0-9a-f][0-9a-f][0-9a-f]/) die("malformed window row " FNR); if(window[$1]++) die("duplicate receiver session: " $1); ws[$1]=$2; wr[$1]=$3; we[$1]=$4; wc[$1]=$5; wf[$1]=$10; wp[$1]=$11; wd[$1]=$12; wphy[$1]=$15; wdev[$1]=$17; wradio[$1]=$18; next }
	FILENAME==meta_file { if(NF!=4 || $1=="" || $2=="" || $3=="" || $4=="") die("malformed metadata row " FNR); k=key($1,$2,$3); if(mseen[k]++) die("duplicate metadata binding"); if(($1=="run" && $2==run && ($3=="candidate_head" || $3=="converter_verified")) || ($1=="phy" && ($2=="tx" || $2=="rx") && $3=="legal_frequencies") || ($1=="transmitter" && $2=="identity" && ($3=="phy" || $3=="interface" || $3=="device" || $3=="radio" || $3=="addr")) || ($1=="frame" && tag($2) && ($3=="frame_control" || $3=="sequence_control")) || ($1=="artifact" && ($3=="path" || $3=="sha256" || $3=="bounded_lines")) || $1=="runtime" || $1=="converter") meta[k]=$4; else die("unknown metadata binding: " $1 "/" $2 "/" $3); next }
	END { if(bad) exit 1; if(!ident(run)||!hp||!hs||!hr||!hl||!hw||!hm) die("missing header or invalid run ID"); if(need("run",run,"candidate_head","candidate head")!=candidate) die("candidate head mismatch"); snapshot("tx",need("phy","tx","legal_frequencies","TX legal snapshot")); snapshot("rx",need("phy","rx","legal_frequencies","RX legal snapshot")); txphy=need("transmitter","identity","phy","TX phy"); txdev=need("transmitter","identity","device","TX device"); txradio=need("transmitter","identity","radio","TX radio"); txaddr=need("transmitter","identity","addr","TX address"); if(need("artifact","probe_plan","path","probe artifact")!=probe_file || need("artifact","send_results","path","send artifact")!=send_file || need("artifact","receiver","path","receiver artifact")!=receiver_file || need("artifact","reflection","path","reflection artifact")!=reflection_file || need("artifact","window","path","window artifact")!=window_file) die("artifact path binding mismatch"); for(t in sent) if(!(t in plan)) die("send tag not predeclared"); for(t in rcv) { if(!(t in plan)) die("receiver tag not predeclared"); capture_count[rs[t]]++ } for(t in local_seen) if(!(t in plan)) die("reflection tag not predeclared"); for(n in required_negative) if(!(n in negative)) die("missing explicit negative control"); for(t in plan) { if(!(tx[t] in txlegal)||!(listen[t] in rxlegal)) die("frequency absent from legal snapshot"); if(!(t in sent)||send_state[t]!="SENT") die("send incomplete"); if(!(t in local_seen)) die("missing local reflection"); if(la[t]!=addr[t]||lfc[t]!=need("frame",t,"frame_control","frame control")||lsc[t]!=need("frame",t,"sequence_control","sequence control")) die("local reflection identity mismatch"); s=session[t]; if(!(s in window)||wf[s]!=listen[t]||send_ts[t]<wr[s]||send_ts[t]>we[s]||wd[s]!=0||wp[s]<capture_count[s]) die("receiver window mismatch"); if(wphy[s]==txphy||wdev[s]==txdev||wradio[s]==txradio) die("receiver is not distinct"); if(expect[t]=="absent") { if(t in rcv) die("negative tag leakage") } else if(t in rcv) { if(rf[t]!=listen[t]||rs[t]!=s||ra[t]!=addr[t]||rfc[t]!=need("frame",t,"frame_control","frame control")||rsc[t]!=need("frame",t,"sequence_control","sequence control")||rt[t]<wr[s]||rt[t]>we[s]) die("receiver identity mismatch"); delivered[tx[t] SUBSEP listen[t] SUBSEP klass[t]]++; received_total++ } } for(m in matrix) if(100*delivered[m]<95*matrix[m]) die("delivery below 95 percent"); if(!bands["2.4"]||!bands["5"]||!bands["6"]) die("missing band coverage"); printf "run_id=%s\npositive_sent=%d\npositive_received=%d\npositive_delivery_percent=%d\nnormalized_status=PASS\n",run,total,received_total,100*received_total/total }
	' "$1" "$2" "$3" "$4" "$5" "$6"); then printf '%s\n' "$result"; else printf '%s\n' "$result" >&2; return 1; fi
}
